import type { Category, DietTag, Difficulty, RecipeStatus } from "../src/lib/constants";

/*
 * Demo data for `pnpm seed`. Recipe text is original; photos are hot-linked from
 * TheMealDB / TheCocktailDB (free, dev-friendly). Swap to Cloudinary for production.
 */

export type SeedAuthor = "priya" | "marco";

export const SEED_USERS: Record<
  SeedAuthor,
  { name: string; username: string; email: string; role: "user" | "admin"; bio: string }
> = {
  priya: {
    name: "Priya Sharma",
    username: "priya_cooks",
    email: "priya@recipehub.test",
    role: "admin",
    bio: "Home cook from Pune. Dal, chai and weekend biryani are my love languages.",
  },
  marco: {
    name: "Marco Rossi",
    username: "marco_rossi",
    email: "marco@recipehub.test",
    role: "user",
    bio: "Pasta purist, curious about every cuisine. Cooking for friends since 2009.",
  },
};

/** Dev-only password for both seed users (override with SEED_USER_PASSWORD). */
export const DEFAULT_SEED_PASSWORD = "RecipeHub123";

export type Ing = { quantity: number | null; unit: string; name: string };
export const i = (quantity: number | null, unit: string, name: string): Ing => ({
  quantity,
  unit,
  name,
});

export interface SeedRecipe {
  title: string;
  description: string;
  coverImage: string;
  cuisine: string;
  category: Category;
  dietTags: DietTag[];
  difficulty: Difficulty;
  prepTime: number;
  cookTime: number;
  servings: number;
  ingredients: Ing[];
  steps: string[];
  tags: string[];
  author: SeedAuthor;
  status?: RecipeStatus;
  /** Spreads createdAt over the past weeks so "newest" ordering looks natural. */
  daysAgo: number;
}

export const MEAL = (id: string) => `https://www.themealdb.com/images/media/meals/${id}.jpg`;
export const DRINK = (id: string) => `https://www.thecocktaildb.com/images/media/drink/${id}.jpg`;

export const SEED_RECIPES: SeedRecipe[] = [
  // ───────────────────────── Indian ─────────────────────────
  {
    title: "Matar Paneer",
    description:
      "Soft paneer cubes and sweet green peas simmered in a gently spiced tomato-onion gravy. A North Indian weeknight classic that pairs with roti or jeera rice.",
    coverImage: MEAL("xxpqsy1511452222"),
    cuisine: "Indian",
    category: "dinner",
    dietTags: ["vegetarian", "gluten-free"],
    difficulty: "easy",
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    ingredients: [
      i(250, "g", "paneer"),
      i(1, "cup", "green peas"),
      i(2, "", "onions"),
      i(3, "", "tomatoes"),
      i(1, "tbsp", "ginger garlic paste"),
      i(1, "tsp", "garam masala"),
      i(1, "tsp", "kashmiri chilli powder"),
      i(0.5, "tsp", "turmeric"),
      i(2, "tbsp", "ghee"),
      i(2, "tbsp", "cream"),
      i(null, "", "salt"),
    ],
    steps: [
      "Cut the paneer into cubes and soak in warm salted water for 10 minutes so it stays soft.",
      "Heat ghee, sauté finely chopped onions until golden, then add ginger garlic paste and cook for a minute.",
      "Add pureed tomatoes, turmeric and chilli powder. Cook until the oil separates, about 8 minutes.",
      "Stir in the peas with 1 cup water, cover and simmer for 5 minutes.",
      "Add the drained paneer, garam masala and salt. Simmer 3 minutes, finish with cream and serve.",
    ],
    tags: ["paneer", "curry", "north indian", "weeknight"],
    author: "priya",
    daysAgo: 2,
  },
  {
    title: "Jain Dal Fry",
    description:
      "Comforting toor dal tempered with ghee, cumin and hing — made without onion, garlic or root vegetables, so it's Jain-friendly and still full of flavour.",
    coverImage: MEAL("wuxrtu1483564410"),
    cuisine: "Indian",
    category: "lunch",
    dietTags: ["vegetarian", "gluten-free", "jain"],
    difficulty: "easy",
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    ingredients: [
      i(1, "cup", "toor dal"),
      i(2, "", "tomatoes"),
      i(1, "", "green chilli"),
      i(1, "tsp", "cumin seeds"),
      i(0.25, "tsp", "hing"),
      i(0.5, "tsp", "turmeric"),
      i(1, "tsp", "red chilli powder"),
      i(2, "tbsp", "ghee"),
      i(2, "tbsp", "coriander leaves"),
      i(1, "tbsp", "lemon juice"),
      i(null, "", "salt"),
    ],
    steps: [
      "Rinse the dal and pressure cook with 3 cups water and turmeric for 4 whistles until soft. Mash lightly.",
      "Heat ghee, add cumin seeds and let them splutter, then add hing and the slit green chilli.",
      "Add chopped tomatoes and chilli powder; cook until the tomatoes break down.",
      "Pour in the cooked dal, add salt and adjust consistency with hot water. Simmer 5 minutes.",
      "Finish with lemon juice and coriander leaves.",
    ],
    tags: ["dal", "lentils", "jain", "comfort food"],
    author: "priya",
    daysAgo: 5,
  },
  {
    title: "Tandoori Chicken",
    description:
      "Chicken legs marinated overnight in yogurt and smoky spices, then roasted until charred at the edges. No tandoor needed — your oven does the job.",
    coverImage: MEAL("qptpvt1487339892"),
    cuisine: "Indian",
    category: "dinner",
    dietTags: ["gluten-free", "keto"],
    difficulty: "medium",
    prepTime: 20,
    cookTime: 35,
    servings: 4,
    ingredients: [
      i(1, "kg", "chicken legs"),
      i(1, "cup", "thick yogurt"),
      i(1, "tbsp", "ginger garlic paste"),
      i(2, "tsp", "kashmiri chilli powder"),
      i(1, "tsp", "garam masala"),
      i(1, "tsp", "cumin powder"),
      i(1, "tbsp", "lemon juice"),
      i(2, "tbsp", "mustard oil"),
      i(null, "", "salt"),
    ],
    steps: [
      "Make deep slashes in the chicken. Rub with lemon juice, salt and chilli powder; rest 20 minutes.",
      "Whisk yogurt with ginger garlic paste, spices and mustard oil. Coat the chicken and refrigerate 6 hours or overnight.",
      "Heat the oven to 240°C (465°F). Arrange chicken on a rack over a tray.",
      "Roast 30–35 minutes, turning once, until charred and cooked through. Baste with oil halfway.",
      "Serve with onion rings, lemon wedges and mint chutney.",
    ],
    tags: ["chicken", "grill", "party", "high protein"],
    author: "priya",
    daysAgo: 9,
  },
  {
    title: "Hyderabadi Lamb Biryani",
    description:
      "Layers of saffron basmati and slow-cooked spiced lamb, sealed and steamed 'dum' style so every grain soaks up the aroma. A weekend project worth every minute.",
    coverImage: MEAL("xrttsx1487339558"),
    cuisine: "Indian",
    category: "dinner",
    dietTags: ["gluten-free"],
    difficulty: "hard",
    prepTime: 45,
    cookTime: 75,
    servings: 6,
    ingredients: [
      i(750, "g", "lamb"),
      i(2, "cups", "basmati rice"),
      i(1, "cup", "yogurt"),
      i(3, "", "onions"),
      i(2, "tbsp", "ginger garlic paste"),
      i(2, "tsp", "biryani masala"),
      i(0.5, "cup", "mint leaves"),
      i(0.5, "cup", "coriander leaves"),
      i(1, "pinch", "saffron"),
      i(0.25, "cup", "warm milk"),
      i(4, "tbsp", "ghee"),
      i(null, "", "whole spices"),
      i(null, "", "salt"),
    ],
    steps: [
      "Marinate lamb with yogurt, ginger garlic paste, biryani masala, half the herbs and salt for at least 2 hours.",
      "Thinly slice onions and fry in ghee until deep golden. Reserve half for layering.",
      "Cook the marinated lamb in a heavy pot with the remaining onions until tender, about 45 minutes.",
      "Boil rice with whole spices and salt until 70% cooked; drain.",
      "Layer rice over the lamb, top with fried onions, herbs and saffron milk. Seal the lid with dough or foil.",
      "Cook on the lowest heat for 25 minutes (dum). Rest 10 minutes before gently mixing and serving.",
    ],
    tags: ["biryani", "rice", "lamb", "festive"],
    author: "priya",
    daysAgo: 14,
  },
  {
    title: "Rajma Masala",
    description:
      "Punjabi-style kidney beans in a thick, tangy onion-tomato masala. The ultimate Sunday lunch with steamed rice.",
    coverImage: MEAL("sywrsu1511463066"),
    cuisine: "Indian",
    category: "lunch",
    dietTags: ["vegan", "vegetarian", "gluten-free"],
    difficulty: "easy",
    prepTime: 15,
    cookTime: 40,
    servings: 4,
    ingredients: [
      i(1, "cup", "kidney beans"),
      i(2, "", "onions"),
      i(3, "", "tomatoes"),
      i(1, "tbsp", "ginger garlic paste"),
      i(1, "tsp", "cumin seeds"),
      i(1, "tsp", "coriander powder"),
      i(1, "tsp", "garam masala"),
      i(1, "tsp", "red chilli powder"),
      i(2, "tbsp", "oil"),
      i(null, "", "salt"),
    ],
    steps: [
      "Soak kidney beans overnight, then pressure cook with salt for 6–7 whistles until creamy inside.",
      "Heat oil, crackle cumin, then fry chopped onions until golden brown.",
      "Add ginger garlic paste, then pureed tomatoes and the powdered spices. Cook until thick and glossy.",
      "Add the beans with their cooking liquid. Mash a few beans to thicken and simmer 15 minutes.",
      "Finish with garam masala and serve with rice.",
    ],
    tags: ["beans", "punjabi", "meal prep", "rajma chawal"],
    author: "priya",
    daysAgo: 20,
  },
  {
    title: "Masala Chai",
    description:
      "Strong Assam tea boiled with milk, fresh ginger and crushed cardamom. The cup that starts a million Indian mornings.",
    coverImage: DRINK("uyrpww1441246384"),
    cuisine: "Indian",
    category: "drink",
    dietTags: ["vegetarian", "gluten-free"],
    difficulty: "easy",
    prepTime: 2,
    cookTime: 8,
    servings: 2,
    ingredients: [
      i(1, "cup", "water"),
      i(1, "cup", "milk"),
      i(2, "tsp", "assam tea leaves"),
      i(1, "inch", "ginger"),
      i(3, "", "green cardamom pods"),
      i(2, "tsp", "sugar"),
    ],
    steps: [
      "Crush the ginger and cardamom lightly with a mortar and pestle.",
      "Bring water to a boil with the ginger and cardamom; simmer 2 minutes.",
      "Add tea leaves and sugar, boil 1 minute until deep amber.",
      "Pour in milk and bring to a rolling boil twice. Strain into cups.",
    ],
    tags: ["tea", "chai", "hot drink"],
    author: "priya",
    daysAgo: 1,
  },
  {
    title: "Mango Lassi",
    description:
      "Thick, chilled yogurt blended with ripe Alphonso mango and a hint of cardamom. Summer in a glass.",
    coverImage: DRINK("1bw6sd1487603816"),
    cuisine: "Indian",
    category: "drink",
    dietTags: ["vegetarian", "gluten-free"],
    difficulty: "easy",
    prepTime: 5,
    cookTime: 0,
    servings: 2,
    ingredients: [
      i(1, "cup", "mango pulp"),
      i(1, "cup", "yogurt"),
      i(0.5, "cup", "cold milk"),
      i(2, "tbsp", "sugar"),
      i(0.25, "tsp", "cardamom powder"),
      i(4, "", "ice cubes"),
    ],
    steps: [
      "Add mango pulp, yogurt, milk, sugar and cardamom to a blender.",
      "Blend with ice until smooth and frothy.",
      "Pour into chilled glasses and garnish with a pinch of cardamom or chopped pistachios.",
    ],
    tags: ["mango", "yogurt", "summer", "no cook"],
    author: "marco",
    daysAgo: 3,
  },

  // ───────────────────────── Italian ─────────────────────────
  {
    title: "Spaghetti alla Carbonara",
    description:
      "The real Roman way: guanciale, egg yolks, Pecorino and black pepper — no cream. Silky, peppery and ready in 20 minutes.",
    coverImage: MEAL("llcbn01574260722"),
    cuisine: "Italian",
    category: "dinner",
    dietTags: [],
    difficulty: "medium",
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    ingredients: [
      i(200, "g", "spaghetti"),
      i(100, "g", "guanciale"),
      i(3, "", "egg yolks"),
      i(1, "", "whole egg"),
      i(50, "g", "pecorino romano"),
      i(1, "tsp", "black pepper"),
      i(null, "", "salt"),
    ],
    steps: [
      "Cook spaghetti in well-salted boiling water until al dente. Reserve a cup of pasta water.",
      "Meanwhile, crisp the diced guanciale in a cold pan brought slowly to medium heat.",
      "Whisk yolks, whole egg, grated pecorino and lots of black pepper into a thick paste.",
      "Off the heat, toss the pasta with the guanciale and its fat, then add the egg mixture.",
      "Toss vigorously, adding splashes of pasta water until glossy and creamy. Serve immediately.",
    ],
    tags: ["pasta", "roman", "quick", "classic"],
    author: "marco",
    daysAgo: 4,
  },
  {
    title: "Pizza Margherita",
    description:
      "A blistered, chewy crust topped with San Marzano tomatoes, fresh mozzarella and basil. Made at home with a screaming-hot oven.",
    coverImage: MEAL("x0lk931587671540"),
    cuisine: "Italian",
    category: "dinner",
    dietTags: ["vegetarian"],
    difficulty: "medium",
    prepTime: 30,
    cookTime: 12,
    servings: 2,
    ingredients: [
      i(300, "g", "pizza flour"),
      i(200, "ml", "warm water"),
      i(3, "g", "dry yeast"),
      i(1, "tsp", "salt"),
      i(200, "g", "san marzano tomatoes"),
      i(150, "g", "fresh mozzarella"),
      i(8, "", "basil leaves"),
      i(2, "tbsp", "olive oil"),
    ],
    steps: [
      "Mix flour, water, yeast and salt into a soft dough. Knead 10 minutes, then let rise 2 hours (or overnight in the fridge).",
      "Heat the oven with a pizza stone or upturned tray at its maximum temperature for 45 minutes.",
      "Crush the tomatoes with a pinch of salt. Stretch the dough by hand into a thin round.",
      "Spread the tomato, add torn mozzarella and a drizzle of olive oil.",
      "Bake 8–12 minutes until the crust is puffed and spotted. Top with basil and serve.",
    ],
    tags: ["pizza", "neapolitan", "baking", "family"],
    author: "marco",
    daysAgo: 7,
  },
  {
    title: "Tuscan Ribollita",
    description:
      "A hearty Tuscan bread-and-bean soup loaded with cavolo nero and vegetables. Even better reheated the next day.",
    coverImage: MEAL("xrrwpx1487347049"),
    cuisine: "Italian",
    category: "lunch",
    dietTags: ["vegan", "vegetarian"],
    difficulty: "easy",
    prepTime: 20,
    cookTime: 50,
    servings: 6,
    ingredients: [
      i(400, "g", "cannellini beans"),
      i(200, "g", "cavolo nero"),
      i(1, "", "onion"),
      i(2, "", "carrots"),
      i(2, "", "celery sticks"),
      i(3, "cloves", "garlic"),
      i(400, "g", "chopped tomatoes"),
      i(4, "slices", "stale bread"),
      i(1, "l", "vegetable stock"),
      i(4, "tbsp", "olive oil"),
      i(null, "", "salt"),
    ],
    steps: [
      "Gently cook diced onion, carrot, celery and garlic in olive oil for 10 minutes.",
      "Add tomatoes, stock and half the beans. Simmer 20 minutes.",
      "Stir in shredded cavolo nero and the remaining beans (mashed) and cook 15 minutes more.",
      "Tear in the stale bread and simmer until it melts into the soup.",
      "Serve drizzled with your best olive oil.",
    ],
    tags: ["soup", "beans", "budget", "tuscan"],
    author: "marco",
    daysAgo: 16,
  },
  {
    title: "Budino di Ricotta",
    description:
      "Little baked ricotta puddings scented with orange zest and cinnamon. Light, creamy and naturally gluten-free.",
    coverImage: MEAL("1549542877"),
    cuisine: "Italian",
    category: "dessert",
    dietTags: ["vegetarian", "gluten-free"],
    difficulty: "easy",
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    ingredients: [
      i(500, "g", "ricotta"),
      i(4, "", "eggs"),
      i(3, "tbsp", "sugar"),
      i(1, "", "orange"),
      i(1, "tsp", "cinnamon"),
      i(1, "tsp", "vanilla extract"),
      i(null, "", "icing sugar"),
    ],
    steps: [
      "Heat the oven to 180°C (350°F) and butter four ramekins.",
      "Beat ricotta with sugar until smooth, then beat in the eggs one at a time.",
      "Fold in orange zest, cinnamon and vanilla.",
      "Divide between ramekins and bake 20–25 minutes until just set with a slight wobble.",
      "Cool slightly and dust with icing sugar before serving.",
    ],
    tags: ["ricotta", "pudding", "citrus"],
    author: "marco",
    daysAgo: 11,
  },

  // ───────────────────────── Mexican ─────────────────────────
  {
    title: "Smoky Chickpea Fajitas",
    description:
      "Crispy smoked-paprika chickpeas with charred peppers and onions, wrapped in warm tortillas. A 25-minute vegan dinner.",
    coverImage: MEAL("tvtxpq1511464705"),
    cuisine: "Mexican",
    category: "dinner",
    dietTags: ["vegan", "vegetarian"],
    difficulty: "easy",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    ingredients: [
      i(400, "g", "chickpeas"),
      i(2, "", "bell peppers"),
      i(1, "", "red onion"),
      i(2, "tsp", "smoked paprika"),
      i(1, "tsp", "cumin powder"),
      i(1, "", "lime"),
      i(8, "", "flour tortillas"),
      i(1, "", "avocado"),
      i(2, "tbsp", "olive oil"),
      i(null, "", "salt"),
    ],
    steps: [
      "Drain and dry the chickpeas, then toss with oil, paprika, cumin and salt.",
      "Fry the chickpeas in a hot pan for 6–8 minutes until crisp; set aside.",
      "In the same pan, char sliced peppers and onion over high heat for 5 minutes.",
      "Return the chickpeas, squeeze over lime and toss.",
      "Serve in warm tortillas with sliced avocado.",
    ],
    tags: ["fajitas", "tortillas", "quick", "plant based"],
    author: "marco",
    daysAgo: 6,
  },
  {
    title: "Stuffed Peppers with Quinoa & Black Beans",
    description:
      "Bell peppers packed with cumin-spiced quinoa, black beans, corn and salsa, then baked until tender.",
    coverImage: MEAL("b66myb1683207208"),
    cuisine: "Mexican",
    category: "lunch",
    dietTags: ["vegan", "vegetarian", "gluten-free"],
    difficulty: "easy",
    prepTime: 15,
    cookTime: 35,
    servings: 4,
    ingredients: [
      i(4, "", "bell peppers"),
      i(1, "cup", "quinoa"),
      i(400, "g", "black beans"),
      i(1, "cup", "sweetcorn"),
      i(1, "cup", "tomato salsa"),
      i(1, "tsp", "cumin powder"),
      i(1, "tsp", "chilli powder"),
      i(2, "tbsp", "coriander leaves"),
      i(null, "", "salt"),
    ],
    steps: [
      "Heat the oven to 190°C (375°F). Cook quinoa in 2 cups water for 15 minutes.",
      "Cut the tops off the peppers and scoop out the seeds.",
      "Mix quinoa with beans, corn, salsa, spices and salt.",
      "Fill the peppers, stand them in a dish with a splash of water and cover with foil.",
      "Bake 30 minutes, uncover for the last 5, and finish with coriander.",
    ],
    tags: ["quinoa", "meal prep", "high fiber"],
    author: "priya",
    daysAgo: 18,
  },

  // ───────────────────────── Chinese ─────────────────────────
  {
    title: "Kung Pao Chicken",
    description:
      "Sichuan stir-fry of tender chicken, roasted peanuts and dried chillies in a glossy sweet-sour-spicy sauce.",
    coverImage: MEAL("1525872624"),
    cuisine: "Chinese",
    category: "dinner",
    dietTags: [],
    difficulty: "medium",
    prepTime: 20,
    cookTime: 10,
    servings: 3,
    ingredients: [
      i(500, "g", "chicken thigh"),
      i(0.5, "cup", "roasted peanuts"),
      i(8, "", "dried red chillies"),
      i(1, "tsp", "sichuan peppercorns"),
      i(3, "", "spring onions"),
      i(2, "tbsp", "soy sauce"),
      i(1, "tbsp", "chinkiang vinegar"),
      i(1, "tbsp", "sugar"),
      i(2, "tsp", "cornflour"),
      i(2, "tbsp", "oil"),
    ],
    steps: [
      "Dice the chicken and marinate with 1 tbsp soy sauce and 1 tsp cornflour for 15 minutes.",
      "Mix the remaining soy sauce, vinegar, sugar, cornflour and 3 tbsp water for the sauce.",
      "Heat oil in a wok, fry chillies and peppercorns for 20 seconds until fragrant.",
      "Add chicken and stir-fry on high heat until just cooked.",
      "Pour in the sauce, toss until glossy, then add peanuts and spring onions.",
    ],
    tags: ["stir fry", "sichuan", "spicy", "wok"],
    author: "marco",
    daysAgo: 8,
  },
  {
    title: "Mapo Tofu",
    description:
      "Silky tofu in a fiery, numbing sauce of doubanjiang, minced pork and Sichuan pepper. Serve over plenty of rice.",
    coverImage: MEAL("1525874812"),
    cuisine: "Chinese",
    category: "dinner",
    dietTags: [],
    difficulty: "medium",
    prepTime: 10,
    cookTime: 15,
    servings: 3,
    ingredients: [
      i(400, "g", "silken tofu"),
      i(150, "g", "minced pork"),
      i(2, "tbsp", "doubanjiang"),
      i(1, "tbsp", "fermented black beans"),
      i(1, "tsp", "ground sichuan pepper"),
      i(3, "cloves", "garlic"),
      i(1, "cup", "chicken stock"),
      i(2, "tsp", "cornflour"),
      i(2, "", "spring onions"),
      i(2, "tbsp", "oil"),
    ],
    steps: [
      "Cut tofu into cubes and blanch in salted simmering water for 2 minutes. Drain gently.",
      "Fry the pork in oil until browned, then add doubanjiang, black beans and garlic.",
      "Pour in stock and slide in the tofu. Simmer 5 minutes without stirring hard.",
      "Thicken with the cornflour slurry in two additions.",
      "Sprinkle Sichuan pepper and spring onions on top.",
    ],
    tags: ["tofu", "sichuan", "spicy"],
    author: "marco",
    daysAgo: 22,
  },
  {
    title: "Smashed Sesame Cucumber Salad",
    description:
      "Smashed cucumbers dressed in garlic, black vinegar, soy and toasted sesame oil. Cold, crunchy and addictive.",
    coverImage: MEAL("93iok31766436070"),
    cuisine: "Chinese",
    category: "snack",
    dietTags: ["vegan", "vegetarian"],
    difficulty: "easy",
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    ingredients: [
      i(2, "", "cucumbers"),
      i(2, "cloves", "garlic"),
      i(1, "tbsp", "soy sauce"),
      i(1, "tbsp", "chinkiang vinegar"),
      i(1, "tsp", "sesame oil"),
      i(1, "tsp", "chilli oil"),
      i(1, "tsp", "sugar"),
      i(1, "tsp", "toasted sesame seeds"),
      i(0.5, "tsp", "salt"),
    ],
    steps: [
      "Smash the cucumbers with the flat of a knife, then cut into bite-size pieces.",
      "Toss with salt and drain in a colander for 10 minutes.",
      "Whisk grated garlic, soy, vinegar, sugar, sesame oil and chilli oil.",
      "Toss the cucumbers in the dressing and top with sesame seeds.",
    ],
    tags: ["salad", "no cook", "side dish"],
    author: "priya",
    daysAgo: 12,
  },

  // ───────────────────────── Thai ─────────────────────────
  {
    title: "Prawn Pad Thai",
    description:
      "Stir-fried rice noodles with prawns, egg, bean sprouts and peanuts, tossed in a tamarind-palm sugar sauce.",
    coverImage: MEAL("rg9ze01763479093"),
    cuisine: "Thai",
    category: "dinner",
    dietTags: ["gluten-free"],
    difficulty: "medium",
    prepTime: 20,
    cookTime: 10,
    servings: 2,
    ingredients: [
      i(150, "g", "flat rice noodles"),
      i(200, "g", "prawns"),
      i(2, "", "eggs"),
      i(2, "tbsp", "tamarind paste"),
      i(2, "tbsp", "fish sauce"),
      i(1.5, "tbsp", "palm sugar"),
      i(1, "cup", "bean sprouts"),
      i(3, "tbsp", "roasted peanuts"),
      i(3, "", "spring onions"),
      i(1, "", "lime"),
      i(2, "tbsp", "oil"),
    ],
    steps: [
      "Soak noodles in warm water for 20 minutes until pliable; drain.",
      "Stir tamarind, fish sauce and palm sugar together until dissolved.",
      "Stir-fry prawns in a hot wok until pink, push aside and scramble the eggs.",
      "Add noodles and sauce; toss for 2–3 minutes until absorbed.",
      "Fold in bean sprouts and spring onions. Serve with crushed peanuts and lime.",
    ],
    tags: ["noodles", "street food", "seafood"],
    author: "marco",
    daysAgo: 10,
  },
  {
    title: "Thai Green Chicken Curry",
    description:
      "Fragrant green curry with chicken, Thai aubergine and basil in creamy coconut milk. Better than takeaway.",
    coverImage: MEAL("sstssx1487349585"),
    cuisine: "Thai",
    category: "dinner",
    dietTags: ["gluten-free"],
    difficulty: "easy",
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    ingredients: [
      i(500, "g", "chicken thigh"),
      i(400, "ml", "coconut milk"),
      i(3, "tbsp", "green curry paste"),
      i(1, "cup", "thai aubergine"),
      i(4, "", "kaffir lime leaves"),
      i(1, "tbsp", "fish sauce"),
      i(1, "tsp", "palm sugar"),
      i(1, "cup", "thai basil"),
      i(1, "tbsp", "oil"),
    ],
    steps: [
      "Fry the curry paste in oil and a few spoons of thick coconut cream until fragrant.",
      "Add sliced chicken and stir to coat.",
      "Pour in the remaining coconut milk with lime leaves; simmer 10 minutes.",
      "Add the aubergine and cook until tender.",
      "Season with fish sauce and palm sugar, then stir in Thai basil.",
    ],
    tags: ["curry", "coconut", "weeknight"],
    author: "priya",
    daysAgo: 13,
  },

  // ───────────────────────── Japanese ─────────────────────────
  {
    title: "Honey Teriyaki Salmon",
    description:
      "Pan-seared salmon glazed in a sticky honey-soy teriyaki. On the table in 20 minutes with rice and greens.",
    coverImage: MEAL("xxyupu1468262513"),
    cuisine: "Japanese",
    category: "dinner",
    dietTags: [],
    difficulty: "easy",
    prepTime: 5,
    cookTime: 15,
    servings: 2,
    ingredients: [
      i(2, "", "salmon fillets"),
      i(3, "tbsp", "soy sauce"),
      i(2, "tbsp", "honey"),
      i(2, "tbsp", "mirin"),
      i(1, "tsp", "grated ginger"),
      i(1, "tsp", "sesame seeds"),
      i(1, "tbsp", "oil"),
    ],
    steps: [
      "Whisk soy sauce, honey, mirin and ginger.",
      "Sear salmon skin-side down in oil for 4 minutes, flip and cook 2 minutes more.",
      "Pour in the sauce and simmer, spooning it over the fish, until sticky.",
      "Garnish with sesame seeds; serve with rice.",
    ],
    tags: ["salmon", "seafood", "quick", "high protein"],
    author: "marco",
    daysAgo: 15,
  },

  // ───────────────────────── Greek ─────────────────────────
  {
    title: "Classic Moussaka",
    description:
      "Layers of roasted aubergine, cinnamon-scented beef ragù and a thick golden béchamel. A Greek showstopper.",
    coverImage: MEAL("ctg8jd1585563097"),
    cuisine: "Greek",
    category: "dinner",
    dietTags: [],
    difficulty: "hard",
    prepTime: 40,
    cookTime: 90,
    servings: 6,
    ingredients: [
      i(3, "", "aubergines"),
      i(500, "g", "minced beef"),
      i(1, "", "onion"),
      i(400, "g", "chopped tomatoes"),
      i(1, "tsp", "cinnamon"),
      i(60, "g", "butter"),
      i(60, "g", "plain flour"),
      i(600, "ml", "milk"),
      i(2, "", "egg yolks"),
      i(50, "g", "parmesan"),
      i(4, "tbsp", "olive oil"),
      i(null, "", "salt"),
    ],
    steps: [
      "Slice aubergines, brush with oil and roast at 200°C (400°F) for 25 minutes.",
      "Brown the beef with onion, add tomatoes and cinnamon, and simmer 30 minutes.",
      "Make béchamel: melt butter, stir in flour, whisk in milk until thick. Beat in yolks and half the cheese.",
      "Layer aubergine and meat sauce in a dish, then top with béchamel and remaining cheese.",
      "Bake at 180°C (350°F) for 45 minutes until golden. Rest 20 minutes before slicing.",
    ],
    tags: ["baked", "beef", "aubergine", "comfort food"],
    author: "marco",
    daysAgo: 25,
  },
  {
    title: "Honey Yogurt Cheesecake",
    description:
      "A lighter, tangy cheesecake made with Greek yogurt and honey on a crunchy biscuit base.",
    coverImage: MEAL("y2irzl1585563479"),
    cuisine: "Greek",
    category: "dessert",
    dietTags: ["vegetarian"],
    difficulty: "medium",
    prepTime: 25,
    cookTime: 50,
    servings: 8,
    ingredients: [
      i(200, "g", "digestive biscuits"),
      i(80, "g", "butter"),
      i(400, "g", "cream cheese"),
      i(300, "g", "greek yogurt"),
      i(100, "g", "honey"),
      i(3, "", "eggs"),
      i(2, "tbsp", "cornflour"),
      i(1, "tsp", "vanilla extract"),
    ],
    steps: [
      "Mix crushed biscuits with melted butter and press into a lined 20 cm tin. Chill 15 minutes.",
      "Beat cream cheese, yogurt, honey, cornflour and vanilla until smooth; beat in eggs.",
      "Pour over the base and bake at 160°C (320°F) for 45–50 minutes until set at the edges.",
      "Turn off the oven and cool inside with the door ajar. Chill overnight.",
      "Drizzle with extra honey before serving.",
    ],
    tags: ["cheesecake", "baking", "honey"],
    author: "priya",
    daysAgo: 19,
  },

  // ───────────────────────── Spanish ─────────────────────────
  {
    title: "Patatas Bravas",
    description:
      "Crispy roasted potatoes with a smoky, spicy tomato bravas sauce. The tapas bar favourite, made easy at home.",
    coverImage: MEAL("bvg8sn1763298713"),
    cuisine: "Spanish",
    category: "snack",
    dietTags: ["vegan", "vegetarian", "gluten-free"],
    difficulty: "easy",
    prepTime: 10,
    cookTime: 40,
    servings: 4,
    ingredients: [
      i(800, "g", "potatoes"),
      i(4, "tbsp", "olive oil"),
      i(1, "", "onion"),
      i(2, "cloves", "garlic"),
      i(400, "g", "chopped tomatoes"),
      i(2, "tsp", "smoked paprika"),
      i(0.5, "tsp", "cayenne pepper"),
      i(1, "tsp", "sherry vinegar"),
      i(null, "", "salt"),
    ],
    steps: [
      "Cut potatoes into chunks, parboil 5 minutes, drain and rough up the edges.",
      "Toss with oil and salt; roast at 220°C (425°F) for 35 minutes until crisp.",
      "Meanwhile, soften onion and garlic, add paprika, cayenne and tomatoes; simmer 15 minutes.",
      "Blend the sauce smooth and stir in sherry vinegar.",
      "Spoon the sauce over the potatoes and serve hot.",
    ],
    tags: ["tapas", "potatoes", "party food"],
    author: "marco",
    daysAgo: 17,
  },

  // ───────────────────────── Breakfast ─────────────────────────
  {
    title: "Shakshuka",
    description:
      "Eggs gently poached in a spiced pepper and tomato sauce. One pan, endless dipping with crusty bread.",
    coverImage: MEAL("g373701551450225"),
    cuisine: "Middle Eastern",
    category: "breakfast",
    dietTags: ["vegetarian", "gluten-free", "keto"],
    difficulty: "easy",
    prepTime: 10,
    cookTime: 20,
    servings: 3,
    ingredients: [
      i(6, "", "eggs"),
      i(1, "", "onion"),
      i(1, "", "red bell pepper"),
      i(3, "cloves", "garlic"),
      i(400, "g", "chopped tomatoes"),
      i(1, "tsp", "cumin powder"),
      i(1, "tsp", "smoked paprika"),
      i(50, "g", "feta"),
      i(2, "tbsp", "olive oil"),
      i(null, "", "salt"),
    ],
    steps: [
      "Soften onion and pepper in olive oil for 8 minutes; add garlic and spices.",
      "Add tomatoes and simmer 10 minutes until thick. Season well.",
      "Make six wells in the sauce and crack in the eggs.",
      "Cover and cook 5–7 minutes until the whites set but yolks are runny.",
      "Crumble over feta and serve straight from the pan.",
    ],
    tags: ["eggs", "one pan", "brunch"],
    author: "priya",
    daysAgo: 6,
  },
  {
    title: "Fluffy Buttermilk Pancakes",
    description:
      "Tall, fluffy American-style pancakes with crisp edges. Stack them high with butter and maple syrup.",
    coverImage: MEAL("rwuyqx1511383174"),
    cuisine: "American",
    category: "breakfast",
    dietTags: ["vegetarian"],
    difficulty: "easy",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    ingredients: [
      i(200, "g", "plain flour"),
      i(2, "tsp", "baking powder"),
      i(0.5, "tsp", "baking soda"),
      i(1, "tbsp", "sugar"),
      i(300, "ml", "buttermilk"),
      i(1, "", "egg"),
      i(30, "g", "butter"),
      i(null, "", "maple syrup"),
    ],
    steps: [
      "Whisk the flour, baking powder, soda, sugar and a pinch of salt.",
      "Whisk buttermilk, egg and melted butter separately, then fold into the dry mix — lumps are fine.",
      "Rest the batter 5 minutes while a non-stick pan heats over medium.",
      "Cook ¼-cup scoops until bubbles pop on top, flip and cook 1 minute more.",
      "Serve warm with butter and maple syrup.",
    ],
    tags: ["pancakes", "brunch", "kids"],
    author: "marco",
    daysAgo: 2,
  },
  {
    title: "French Omelette",
    description:
      "A smooth, pale, custardy omelette rolled the classic French way. A two-minute lesson in technique.",
    coverImage: MEAL("yvpuuy1511797244"),
    cuisine: "French",
    category: "breakfast",
    dietTags: ["vegetarian", "gluten-free", "keto"],
    difficulty: "medium",
    prepTime: 2,
    cookTime: 3,
    servings: 1,
    ingredients: [
      i(3, "", "eggs"),
      i(1, "tbsp", "butter"),
      i(1, "tsp", "chives"),
      i(null, "", "salt"),
      i(null, "", "white pepper"),
    ],
    steps: [
      "Beat eggs with a pinch of salt until completely uniform.",
      "Melt butter in a non-stick pan over medium-low until foaming.",
      "Add eggs and stir constantly with a spatula while shaking the pan to form small curds.",
      "When almost set, smooth the surface, then roll the omelette towards the pan edge.",
      "Turn onto a plate seam-side down and finish with chives and a little butter.",
    ],
    tags: ["eggs", "technique", "quick"],
    author: "marco",
    daysAgo: 21,
  },

  // ───────────────────────── Draft (only visible to its author later) ─────────────────────────
  {
    title: "Moroccan Lamb Tagine",
    description:
      "Slow-cooked lamb with apricots, warm spices and toasted almonds. Still perfecting the spice balance — draft!",
    coverImage: MEAL("yuwtuu1511295751"),
    cuisine: "Moroccan",
    category: "dinner",
    dietTags: ["gluten-free"],
    difficulty: "medium",
    prepTime: 20,
    cookTime: 120,
    servings: 4,
    ingredients: [
      i(800, "g", "lamb shoulder"),
      i(2, "", "onions"),
      i(1, "cup", "dried apricots"),
      i(2, "tsp", "ras el hanout"),
      i(1, "tsp", "cinnamon"),
      i(400, "g", "chopped tomatoes"),
      i(0.5, "cup", "toasted almonds"),
    ],
    steps: [
      "Brown the lamb in batches and set aside.",
      "Soften onions with the spices, return the lamb with tomatoes and water to cover.",
      "Cover and cook gently for 1½ hours, add apricots and cook 30 minutes more.",
      "Scatter with almonds and serve with couscous.",
    ],
    tags: ["slow cooked", "lamb", "stew"],
    author: "priya",
    status: "draft",
    daysAgo: 0,
  },
];
