import { MEAL, i, type SeedRecipe } from "./seed-data";

/** Demo "submitted" recipes for an existing account — used by `pnpm seed:user <username>`. */
export type UserSeedRecipe = Omit<SeedRecipe, "author">;

export const USER_RECIPES: UserSeedRecipe[] = [
  {
    title: "Chicken Handi",
    description:
      "Creamy, mildly spiced chicken curry slow-cooked in a clay handi with yogurt, cream and kasuri methi. My go-to for family dinners.",
    coverImage: MEAL("wyxwsp1486979827"),
    cuisine: "Indian",
    category: "dinner",
    dietTags: ["gluten-free"],
    difficulty: "medium",
    prepTime: 20,
    cookTime: 35,
    servings: 4,
    ingredients: [
      i(750, "g", "chicken"),
      i(2, "", "onions"),
      i(2, "", "tomatoes"),
      i(0.5, "cup", "yogurt"),
      i(0.25, "cup", "cream"),
      i(1, "tbsp", "ginger garlic paste"),
      i(2, "", "green chillies"),
      i(1, "tsp", "garam masala"),
      i(1, "tsp", "coriander powder"),
      i(1, "tbsp", "kasuri methi"),
      i(3, "tbsp", "oil"),
      i(null, "", "salt"),
    ],
    steps: [
      "Heat oil in a handi or heavy pot and fry sliced onions until golden.",
      "Add ginger garlic paste and slit green chillies; sauté for a minute.",
      "Add the chicken and sear on high heat for 5 minutes until it changes colour.",
      "Stir in chopped tomatoes, coriander powder and salt. Cover and cook 15 minutes.",
      "Lower the heat, stir in whisked yogurt and cook 10 minutes more.",
      "Finish with cream, garam masala and crushed kasuri methi. Rest 5 minutes before serving.",
    ],
    tags: ["chicken", "curry", "creamy", "family dinner"],
    daysAgo: 1,
  },
  {
    title: "Kashmiri Lamb Rogan Josh",
    description:
      "Tender lamb braised in a deep red gravy of Kashmiri chillies, fennel and dry ginger — rich in colour, gentle in heat.",
    coverImage: MEAL("vvstvq1487342592"),
    cuisine: "Indian",
    category: "dinner",
    dietTags: ["gluten-free"],
    difficulty: "hard",
    prepTime: 20,
    cookTime: 90,
    servings: 4,
    ingredients: [
      i(800, "g", "lamb"),
      i(1, "cup", "yogurt"),
      i(2, "tbsp", "kashmiri chilli powder"),
      i(1, "tsp", "fennel powder"),
      i(1, "tsp", "dry ginger powder"),
      i(4, "", "green cardamom pods"),
      i(2, "", "black cardamom pods"),
      i(4, "", "cloves"),
      i(1, "", "cinnamon stick"),
      i(0.25, "tsp", "hing"),
      i(4, "tbsp", "mustard oil"),
      i(null, "", "salt"),
    ],
    steps: [
      "Heat mustard oil until it smokes, then let it cool slightly.",
      "Fry the whole spices and hing for 30 seconds, then brown the lamb in batches.",
      "Mix chilli powder with a little water into a paste, add to the pot and cook 2 minutes.",
      "Whisk yogurt with fennel and dry ginger; add gradually, stirring so it doesn't split.",
      "Add 2 cups hot water and salt, cover and simmer 75–90 minutes until the lamb is tender.",
      "Uncover and reduce until the gravy is glossy and the oil rises to the top.",
    ],
    tags: ["lamb", "kashmiri", "slow cooked", "festive"],
    daysAgo: 4,
  },
  {
    title: "Tahini Lentils",
    description:
      "Warm green lentils tossed with a lemony tahini dressing, roasted peppers and fresh herbs. Great hot or as a packed lunch.",
    coverImage: MEAL("vpxyqt1511464175"),
    cuisine: "Moroccan",
    category: "lunch",
    dietTags: ["vegan", "vegetarian", "gluten-free"],
    difficulty: "easy",
    prepTime: 10,
    cookTime: 25,
    servings: 3,
    ingredients: [
      i(1, "cup", "green lentils"),
      i(3, "tbsp", "tahini"),
      i(1, "", "lemon"),
      i(1, "clove", "garlic"),
      i(1, "", "red bell pepper"),
      i(1, "", "red onion"),
      i(0.5, "cup", "parsley"),
      i(1, "tsp", "cumin powder"),
      i(2, "tbsp", "olive oil"),
      i(null, "", "salt"),
    ],
    steps: [
      "Simmer the lentils in plenty of water for 20–25 minutes until just tender; drain.",
      "Roast or pan-char the sliced pepper and onion with olive oil and cumin.",
      "Whisk tahini, lemon juice, grated garlic, salt and 3–4 tbsp warm water until creamy.",
      "Toss the warm lentils with the vegetables and dressing.",
      "Fold in chopped parsley and serve warm or at room temperature.",
    ],
    tags: ["lentils", "meal prep", "high protein", "plant based"],
    daysAgo: 7,
  },
  {
    title: "Crispy Breakfast Potatoes",
    description:
      "Golden skillet potatoes with peppers, onions and smoked paprika. The perfect side for eggs — or eaten straight from the pan.",
    coverImage: MEAL("1550441882"),
    cuisine: "American",
    category: "breakfast",
    dietTags: ["vegan", "vegetarian", "gluten-free"],
    difficulty: "easy",
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    ingredients: [
      i(700, "g", "potatoes"),
      i(1, "", "green bell pepper"),
      i(1, "", "onion"),
      i(1, "tsp", "smoked paprika"),
      i(0.5, "tsp", "garlic powder"),
      i(3, "tbsp", "olive oil"),
      i(2, "tbsp", "parsley"),
      i(null, "", "salt"),
      i(null, "", "black pepper"),
    ],
    steps: [
      "Dice the potatoes into 2 cm cubes and microwave or parboil for 5 minutes until barely tender.",
      "Heat oil in a large skillet and add the potatoes in a single layer. Don't stir for 5 minutes.",
      "Flip and add diced onion and pepper; cook 10 more minutes until crisp all over.",
      "Season with paprika, garlic powder, salt and pepper, then toss with parsley.",
    ],
    tags: ["potatoes", "brunch", "one pan", "budget"],
    daysAgo: 10,
  },
  {
    title: "Chicken Quinoa Greek Salad",
    description:
      "Lemon-oregano chicken over fluffy quinoa with cucumber, tomatoes, olives and feta. A filling, high-protein lunch bowl.",
    coverImage: MEAL("k29viq1585565980"),
    cuisine: "Greek",
    category: "lunch",
    dietTags: ["gluten-free"],
    difficulty: "easy",
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    ingredients: [
      i(2, "", "chicken breasts"),
      i(0.75, "cup", "quinoa"),
      i(1, "", "cucumber"),
      i(1, "cup", "cherry tomatoes"),
      i(0.5, "cup", "kalamata olives"),
      i(80, "g", "feta"),
      i(0.5, "", "red onion"),
      i(1, "", "lemon"),
      i(1, "tsp", "dried oregano"),
      i(3, "tbsp", "olive oil"),
      i(null, "", "salt"),
    ],
    steps: [
      "Cook quinoa in 1½ cups water for 15 minutes, then fluff and cool slightly.",
      "Rub chicken with oil, oregano, lemon zest and salt; grill or pan-fry 5–6 minutes per side. Rest and slice.",
      "Chop cucumber, halve tomatoes and thinly slice the red onion.",
      "Whisk lemon juice with olive oil and a pinch of oregano.",
      "Toss quinoa and vegetables with the dressing, top with chicken, olives and crumbled feta.",
    ],
    tags: ["salad", "high protein", "meal prep", "healthy"],
    daysAgo: 13,
  },
  {
    title: "Beef Lo Mein",
    description:
      "Silky egg noodles stir-fried with tender beef, crunchy vegetables and a savoury oyster-soy sauce. Still tweaking the sauce ratio — draft.",
    coverImage: MEAL("1529444830"),
    cuisine: "Chinese",
    category: "dinner",
    dietTags: [],
    difficulty: "medium",
    prepTime: 20,
    cookTime: 10,
    servings: 3,
    ingredients: [
      i(250, "g", "egg noodles"),
      i(300, "g", "flank steak"),
      i(1, "", "carrot"),
      i(1, "cup", "cabbage"),
      i(4, "", "spring onions"),
      i(2, "tbsp", "soy sauce"),
      i(1, "tbsp", "oyster sauce"),
      i(1, "tsp", "sesame oil"),
      i(1, "tsp", "cornflour"),
      i(2, "tbsp", "oil"),
    ],
    steps: [
      "Thinly slice the beef against the grain and toss with 1 tsp soy sauce and the cornflour.",
      "Cook the noodles, drain and toss with sesame oil.",
      "Sear the beef in a very hot wok for 1–2 minutes; remove.",
      "Stir-fry the vegetables for 2 minutes, then add noodles, beef and the remaining sauces.",
      "Toss over high heat until glossy and finish with spring onions.",
    ],
    tags: ["noodles", "stir fry", "beef", "wok"],
    status: "draft",
    daysAgo: 0,
  },
];
